swagger: '2.0'
info:
  title: Global Definitions
  version: '1.0.0'
paths: {}
definitions:
  genericError:
    properties:
      message:
        type: string
        description: Identifica el problema con un mensaje.
        example: Client id or Secret are invalid
      code:
        type: string
        description: 'Codigo de error, usado para interpretaciones de aplicaci贸n'
        example: '401'
    additionalProperties: false
    description: >-
      Indica que los client id son invalidos o que no existe suscripci贸n
      aprobada.
    required:
      - message
      - code
  money:
    properties:
      amount:
        type: number
        format: decimal
        example: '248750.00'
        description: Monto de la transacci贸n
      currency:
        type: string
        example: CLP
        description: Tipo de moneda - ISO 4217
    additionalProperties: false
    description: Contiene los atributos del monto de una transacci贸n
    required:
      - amount
      - currency
